site_name: ResMicroDb documentation
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    - toc.integrate 


# Page tree
nav:
  - Welcome & key features: index.md
  - Home: Home.md
  - Search: Search.md
  - Browse: Browse.md
  - Analysis: Analysis.md
